name: Build CV
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Emre CV - Build (EN)
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./emre-cv
          root_file: |
            index.en.tex
      - name: Emre CV - Build (TR)
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./emre-cv
          root_file: |
            index.tr.tex
      - name: Burak CV - Build
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./burak-cv
          root_file: |
            index.tex
      - name: Prepare Deployment
        run: |
          mkdir build
          cp emre-cv/index.en.pdf build/mehmet-arif-emre-sen.pdf
          cp emre-cv/index.tr.pdf build/mehmet-arif-emre-sen-tr.pdf
          cp burak-cv/index.pdf build/burak-erkan.pdf
          echo "cv.yazilim.vip" > ./build/CNAME
      - name: GH Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
