name: Build CV
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Emre CV - Build
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./emre-cv
          root_file: |
            index.tex
      - name: Burak CV - Build
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./burak-cv
          root_file: |
            index.tex
      - name: Prepare Deployment
        run: |
          mkdir build
          cp emre-cv/index.pdf build/cv_mehmet_arif_emre_sen.pdf
          cp burak-cv/index.pdf build/cv_burak_erkan.pdf
      - name: GH Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
